//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBucket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBucket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is MusicBucket
        ///Version: {0}, Built: {1}
        ///What would be the world be like if people could move around as openly as this piece of software can? Think about it!.
        /// </summary>
        public static string AboutDialogText {
            get {
                return ResourceManager.GetString("AboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string addBucketButtonText {
            get {
                return ResourceManager.GetString("addBucketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicBucket.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bouncyness value (currenty {0}) must be within 0 and 0.5.
        /// </summary>
        public static string BouncynessValueOutOfRange {
            get {
                return ResourceManager.GetString("BouncynessValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket Organization.
        /// </summary>
        public static string BucketColumnDisplay {
            get {
                return ResourceManager.GetString("BucketColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to excluding subfolders.
        /// </summary>
        public static string BucketDescriptionExcludingSubfolders {
            get {
                return ResourceManager.GetString("BucketDescriptionExcludingSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to including subfolders.
        /// </summary>
        public static string BucketDescriptionIncludingSubfolders {
            get {
                return ResourceManager.GetString("BucketDescriptionIncludingSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string BucketDescriptionPathPrefix {
            get {
                return ResourceManager.GetString("BucketDescriptionPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BucketDescriptionTitlePrefix {
            get {
                return ResourceManager.GetString("BucketDescriptionTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Types.
        /// </summary>
        public static string BucketLVTagTypes {
            get {
                return ResourceManager.GetString("BucketLVTagTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose CDDB Entry.
        /// </summary>
        public static string CDDBEntryChooserTitle {
            get {
                return ResourceManager.GetString("CDDBEntryChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drives.
        /// </summary>
        public static string CDDriveLabel {
            get {
                return ResourceManager.GetString("CDDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue.
        /// </summary>
        public static string continueImportText {
            get {
                return ResourceManager.GetString("continueImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to something bad happened during copying of mp3 to bucket located at {}, is the bucket writeable?.
        /// </summary>
        public static string copyToBucketError {
            get {
                return ResourceManager.GetString("copyToBucketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Bucket.
        /// </summary>
        public static string FileMenuAddBucket {
            get {
                return ResourceManager.GetString("FileMenuAddBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Bucket.
        /// </summary>
        public static string FileMenuOpenBucket {
            get {
                return ResourceManager.GetString("FileMenuOpenBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuTitle {
            get {
                return ResourceManager.GetString("FileMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string FolderBrowserDialogTitle {
            get {
                return ResourceManager.GetString("FolderBrowserDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content of Frame.
        /// </summary>
        public static string frameContent {
            get {
                return ResourceManager.GetString("frameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame List of ID3v23 Tag.
        /// </summary>
        public static string frameListDialogTitle {
            get {
                return ResourceManager.GetString("frameListDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame List of ID3v22 Tag.
        /// </summary>
        public static string frameListDialogTitleV22 {
            get {
                return ResourceManager.GetString("frameListDialogTitleV22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frequency of the animation bounce must be within 1 and 2134.
        /// </summary>
        public static string FrequencyOutOfRange {
            get {
                return ResourceManager.GetString("FrequencyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpMenuTitle {
            get {
                return ResourceManager.GetString("HelpMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string ImportColumnDisplay {
            get {
                return ResourceManager.GetString("ImportColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string ImportLVColumnAlbum {
            get {
                return ResourceManager.GetString("ImportLVColumnAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        public static string ImportLVColumnArtist {
            get {
                return ResourceManager.GetString("ImportLVColumnArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string ImportLVColumnGenre {
            get {
                return ResourceManager.GetString("ImportLVColumnGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Nr.
        /// </summary>
        public static string ImportLVColumnTrackNr {
            get {
                return ResourceManager.GetString("ImportLVColumnTrackNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Title.
        /// </summary>
        public static string ImportLVColumnTrackTitle {
            get {
                return ResourceManager.GetString("ImportLVColumnTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ImportLVColumnYear {
            get {
                return ResourceManager.GetString("ImportLVColumnYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An import is already on the way, wait for it to finish before starting a new one.
        /// </summary>
        public static string importProcessRunning {
            get {
                return ResourceManager.GetString("importProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A CD is currently imported, MusicBucket cannot be closed.
        /// </summary>
        public static string importRunning {
            get {
                return ResourceManager.GetString("importRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write ID3v1 Tags.
        /// </summary>
        public static string ImportSettingsDialogCheckBoxV1 {
            get {
                return ResourceManager.GetString("ImportSettingsDialogCheckBoxV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to write ID3v2 Tags.
        /// </summary>
        public static string ImportSettingsDialogCheckBoxV2 {
            get {
                return ResourceManager.GetString("ImportSettingsDialogCheckBoxV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Quality.
        /// </summary>
        public static string ImportSettingsDialogImportQuality {
            get {
                return ResourceManager.GetString("ImportSettingsDialogImportQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Bitrate Chosen.
        /// </summary>
        public static string ImportSettingsDialogInvalidBitrate {
            get {
                return ResourceManager.GetString("ImportSettingsDialogInvalidBitrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3v22.
        /// </summary>
        public static string ImportSettingsDialogRBID3v22 {
            get {
                return ResourceManager.GetString("ImportSettingsDialogRBID3v22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID3v23.
        /// </summary>
        public static string ImportSettingsDialogRBID3v23 {
            get {
                return ResourceManager.GetString("ImportSettingsDialogRBID3v23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Settings.
        /// </summary>
        public static string ImportSettingsDialogTitle {
            get {
                return ResourceManager.GetString("ImportSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import terminated.
        /// </summary>
        public static string importTerminated {
            get {
                return ResourceManager.GetString("importTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Compressed.
        /// </summary>
        public static string iscompressed {
            get {
                return ResourceManager.GetString("iscompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Encrypted.
        /// </summary>
        public static string isencrypted {
            get {
                return ResourceManager.GetString("isencrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Grouped.
        /// </summary>
        public static string isGrouped {
            get {
                return ResourceManager.GetString("isGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit new Bucket.
        /// </summary>
        public static string NewBucketDialogButtonOK {
            get {
                return ResourceManager.GetString("NewBucketDialogButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Subfolder.
        /// </summary>
        public static string NewBucketDialogIncludeSubfolders {
            get {
                return ResourceManager.GetString("NewBucketDialogIncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select...
        /// </summary>
        public static string NewBucketDialogSelectFolder {
            get {
                return ResourceManager.GetString("NewBucketDialogSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Bucket.
        /// </summary>
        public static string NewBucketDialogTitle {
            get {
                return ResourceManager.GetString("NewBucketDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of Bucket.
        /// </summary>
        public static string NewBucketDialogTitleTitle {
            get {
                return ResourceManager.GetString("NewBucketDialogTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music should always be placed in buckets, please select at least one.
        /// </summary>
        public static string noBucketSelectedText {
            get {
                return ResourceManager.GetString("noBucketSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Entry on CDDB database found.
        /// </summary>
        public static string NoCDDBEntriesFound {
            get {
                return ResourceManager.GetString("NoCDDBEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a CD drive.
        /// </summary>
        public static string NoCDDriveSelected {
            get {
                return ResourceManager.GetString("NoCDDriveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CD has been inserted or cd is not readable.
        /// </summary>
        public static string NoCDInserted {
            get {
                return ResourceManager.GetString("NoCDInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string PlayerColumnDisplay {
            get {
                return ResourceManager.GetString("PlayerColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pres. if file alters.
        /// </summary>
        public static string preserveWhenFileAlters {
            get {
                return ResourceManager.GetString("preserveWhenFileAlters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pres. if tag alters.
        /// </summary>
        public static string preserveWhenTagAlters {
            get {
                return ResourceManager.GetString("preserveWhenTagAlters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion of track .
        /// </summary>
        public static string ProgressConversion {
            get {
                return ResourceManager.GetString("ProgressConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripping of track .
        /// </summary>
        public static string ProgressImport {
            get {
                return ResourceManager.GetString("ProgressImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to readOnly.
        /// </summary>
        public static string readOnly {
            get {
                return ResourceManager.GetString("readOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove the selected bucket?.
        /// </summary>
        public static string ReallyRemoveBucket {
            get {
                return ResourceManager.GetString("ReallyRemoveBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Bucket!?.
        /// </summary>
        public static string ReallyRemoveBucketTitle {
            get {
                return ResourceManager.GetString("ReallyRemoveBucketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string removeBucketButtonText {
            get {
                return ResourceManager.GetString("removeBucketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string SettingsMenuImportSettings {
            get {
                return ResourceManager.GetString("SettingsMenuImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsMenuText {
            get {
                return ResourceManager.GetString("SettingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals.
        /// </summary>
        public static string SettingsMenuVisuals {
            get {
                return ResourceManager.GetString("SettingsMenuVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saving error.
        /// </summary>
        public static string SettingsNotSavedMsgBoxTitle {
            get {
                return ResourceManager.GetString("SettingsNotSavedMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sharpness value (currently {0}) must be within 0 and 1 (1 excluded).
        /// </summary>
        public static string SharpnessValueOutOfRange {
            get {
                return ResourceManager.GetString("SharpnessValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame List.
        /// </summary>
        public static string showFrameList {
            get {
                return ResourceManager.GetString("showFrameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start!!.
        /// </summary>
        public static string startImportText {
            get {
                return ResourceManager.GetString("startImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings couldn&apos;t not be read or created. Make sure that the harddrive of the computer is not full..
        /// </summary>
        public static string UserSettingsNotOpened {
            get {
                return ResourceManager.GetString("UserSettingsNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings couldn&apos;t not be saved. Make sure that the harddrive of the computer is not full. Do you still want to exit?.
        /// </summary>
        public static string UserSettingsNotSaved {
            get {
                return ResourceManager.GetString("UserSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals settings.
        /// </summary>
        public static string VisualsSettingsDialogTitle {
            get {
                return ResourceManager.GetString("VisualsSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharpness
        ///Frequency
        ///Bouncyness.
        /// </summary>
        public static string VisualsSettingsLabels {
            get {
                return ResourceManager.GetString("VisualsSettingsLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number could not be read, make sure to use the correct comma separator (&apos;,&apos; in german).
        /// </summary>
        public static string VisualsSettingsNumbersNotParsed {
            get {
                return ResourceManager.GetString("VisualsSettingsNumbersNotParsed", resourceCulture);
            }
        }
    }
}
