//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34011
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicBucket.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicBucket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is MusicBucket
        ///Version: {0}, Built: {1}
        ///I believe that music should be placed in buckets and that the world would be a better place if everyone has free decision on where she or he want to live. So please support organizations such as http://www.bleiberecht.ch ähnelt.
        /// </summary>
        public static string AboutDialogText {
            get {
                return ResourceManager.GetString("AboutDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string addBucketButtonText {
            get {
                return ResourceManager.GetString("addBucketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MusicBucket ähnelt.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Bouncyness value (currenty {0}) must be within 0 and 0.5 ähnelt.
        /// </summary>
        public static string BouncynessValueOutOfRange {
            get {
                return ResourceManager.GetString("BouncynessValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bucket Organization ähnelt.
        /// </summary>
        public static string BucketColumnDisplay {
            get {
                return ResourceManager.GetString("BucketColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die excluding subfolders ähnelt.
        /// </summary>
        public static string BucketDescriptionExcludingSubfolders {
            get {
                return ResourceManager.GetString("BucketDescriptionExcludingSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die including subfolders ähnelt.
        /// </summary>
        public static string BucketDescriptionIncludingSubfolders {
            get {
                return ResourceManager.GetString("BucketDescriptionIncludingSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path ähnelt.
        /// </summary>
        public static string BucketDescriptionPathPrefix {
            get {
                return ResourceManager.GetString("BucketDescriptionPathPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string BucketDescriptionTitlePrefix {
            get {
                return ResourceManager.GetString("BucketDescriptionTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bucket List couldn&apos;t not be read or created. Make sure that the harddrive of the computer is not full. ähnelt.
        /// </summary>
        public static string BucketListNotOpened {
            get {
                return ResourceManager.GetString("BucketListNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bucket List couldn&apos;t not be saved. Make sure that the harddrive of the computer is not full. Do you still want to exit? ähnelt.
        /// </summary>
        public static string BucketListNotSaved {
            get {
                return ResourceManager.GetString("BucketListNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bucket List saving error ähnelt.
        /// </summary>
        public static string BucketListNotSavedMsgBoxTitle {
            get {
                return ResourceManager.GetString("BucketListNotSavedMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tag Types ähnelt.
        /// </summary>
        public static string BucketLVTagTypes {
            get {
                return ResourceManager.GetString("BucketLVTagTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose CDDB Entry ähnelt.
        /// </summary>
        public static string CDDBEntryChooserTitle {
            get {
                return ResourceManager.GetString("CDDBEntryChooserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drives ähnelt.
        /// </summary>
        public static string CDDriveLabel {
            get {
                return ResourceManager.GetString("CDDriveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die continue ähnelt.
        /// </summary>
        public static string continueImportText {
            get {
                return ResourceManager.GetString("continueImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die something bad happened during copying of mp3 to bucket located at {}, is the bucket writeable? ähnelt.
        /// </summary>
        public static string copyToBucketError {
            get {
                return ResourceManager.GetString("copyToBucketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Bucket ähnelt.
        /// </summary>
        public static string FileMenuAddBucket {
            get {
                return ResourceManager.GetString("FileMenuAddBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string FileMenuClose {
            get {
                return ResourceManager.GetString("FileMenuClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Bucket ähnelt.
        /// </summary>
        public static string FileMenuOpenBucket {
            get {
                return ResourceManager.GetString("FileMenuOpenBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string FileMenuTitle {
            get {
                return ResourceManager.GetString("FileMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Name ähnelt.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Folder ähnelt.
        /// </summary>
        public static string FolderBrowserDialogTitle {
            get {
                return ResourceManager.GetString("FolderBrowserDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Content of Frame ähnelt.
        /// </summary>
        public static string frameContent {
            get {
                return ResourceManager.GetString("frameContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frame List of ID3v23 Tag ähnelt.
        /// </summary>
        public static string frameListDialogTitle {
            get {
                return ResourceManager.GetString("frameListDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frame List of ID3v22 Tag ähnelt.
        /// </summary>
        public static string frameListDialogTitleV22 {
            get {
                return ResourceManager.GetString("frameListDialogTitleV22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The frequency of the animation bounce must be within 1 and 2134 ähnelt.
        /// </summary>
        public static string FrequencyOutOfRange {
            get {
                return ResourceManager.GetString("FrequencyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About... ähnelt.
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        public static string HelpMenuTitle {
            get {
                return ResourceManager.GetString("HelpMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string ImportColumnDisplay {
            get {
                return ResourceManager.GetString("ImportColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Album ähnelt.
        /// </summary>
        public static string ImportLVColumnAlbum {
            get {
                return ResourceManager.GetString("ImportLVColumnAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Artist ähnelt.
        /// </summary>
        public static string ImportLVColumnArtist {
            get {
                return ResourceManager.GetString("ImportLVColumnArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Genre ähnelt.
        /// </summary>
        public static string ImportLVColumnGenre {
            get {
                return ResourceManager.GetString("ImportLVColumnGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Nr ähnelt.
        /// </summary>
        public static string ImportLVColumnTrackNr {
            get {
                return ResourceManager.GetString("ImportLVColumnTrackNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Track Title ähnelt.
        /// </summary>
        public static string ImportLVColumnTrackTitle {
            get {
                return ResourceManager.GetString("ImportLVColumnTrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Year ähnelt.
        /// </summary>
        public static string ImportLVColumnYear {
            get {
                return ResourceManager.GetString("ImportLVColumnYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An import is already on the way, wait for it to finish before starting a new one ähnelt.
        /// </summary>
        public static string importProcessRunning {
            get {
                return ResourceManager.GetString("importProcessRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A CD is currently imported, MusicBucket cannot be closed ähnelt.
        /// </summary>
        public static string importRunning {
            get {
                return ResourceManager.GetString("importRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import terminated ähnelt.
        /// </summary>
        public static string importTerminated {
            get {
                return ResourceManager.GetString("importTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Compressed ähnelt.
        /// </summary>
        public static string iscompressed {
            get {
                return ResourceManager.GetString("iscompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Encrypted ähnelt.
        /// </summary>
        public static string isencrypted {
            get {
                return ResourceManager.GetString("isencrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Grouped ähnelt.
        /// </summary>
        public static string isGrouped {
            get {
                return ResourceManager.GetString("isGrouped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commit new Bucket ähnelt.
        /// </summary>
        public static string NewBucketDialogButtonOK {
            get {
                return ResourceManager.GetString("NewBucketDialogButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Include Subfolder ähnelt.
        /// </summary>
        public static string NewBucketDialogIncludeSubfolders {
            get {
                return ResourceManager.GetString("NewBucketDialogIncludeSubfolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select.. ähnelt.
        /// </summary>
        public static string NewBucketDialogSelectFolder {
            get {
                return ResourceManager.GetString("NewBucketDialogSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Bucket ähnelt.
        /// </summary>
        public static string NewBucketDialogTitle {
            get {
                return ResourceManager.GetString("NewBucketDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title of Bucket ähnelt.
        /// </summary>
        public static string NewBucketDialogTitleTitle {
            get {
                return ResourceManager.GetString("NewBucketDialogTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Music should always be placed in buckets, please select at least one ähnelt.
        /// </summary>
        public static string noBucketSelectedText {
            get {
                return ResourceManager.GetString("noBucketSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Entry on CDDB database found ähnelt.
        /// </summary>
        public static string NoCDDBEntriesFound {
            get {
                return ResourceManager.GetString("NoCDDBEntriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a CD drive ähnelt.
        /// </summary>
        public static string NoCDDriveSelected {
            get {
                return ResourceManager.GetString("NoCDDriveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No CD has been inserted or cd is not readable ähnelt.
        /// </summary>
        public static string NoCDInserted {
            get {
                return ResourceManager.GetString("NoCDInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player ähnelt.
        /// </summary>
        public static string PlayerColumnDisplay {
            get {
                return ResourceManager.GetString("PlayerColumnDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pres. if file alters ähnelt.
        /// </summary>
        public static string preserveWhenFileAlters {
            get {
                return ResourceManager.GetString("preserveWhenFileAlters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pres. if tag alters ähnelt.
        /// </summary>
        public static string preserveWhenTagAlters {
            get {
                return ResourceManager.GetString("preserveWhenTagAlters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conversion of track  ähnelt.
        /// </summary>
        public static string ProgressConversion {
            get {
                return ResourceManager.GetString("ProgressConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ripping of track  ähnelt.
        /// </summary>
        public static string ProgressImport {
            get {
                return ResourceManager.GetString("ProgressImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die readOnly ähnelt.
        /// </summary>
        public static string readOnly {
            get {
                return ResourceManager.GetString("readOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to remove the selected bucket? ähnelt.
        /// </summary>
        public static string ReallyRemoveBucket {
            get {
                return ResourceManager.GetString("ReallyRemoveBucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Bucket!? ähnelt.
        /// </summary>
        public static string ReallyRemoveBucketTitle {
            get {
                return ResourceManager.GetString("ReallyRemoveBucketTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string removeBucketButtonText {
            get {
                return ResourceManager.GetString("removeBucketButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import ähnelt.
        /// </summary>
        public static string SettingsMenuImportSettings {
            get {
                return ResourceManager.GetString("SettingsMenuImportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsMenuText {
            get {
                return ResourceManager.GetString("SettingsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visuals ähnelt.
        /// </summary>
        public static string SettingsMenuVisuals {
            get {
                return ResourceManager.GetString("SettingsMenuVisuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The sharpness value (currently {0}) must be within 0 and 1 (1 excluded) ähnelt.
        /// </summary>
        public static string SharpnessValueOutOfRange {
            get {
                return ResourceManager.GetString("SharpnessValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frame List ähnelt.
        /// </summary>
        public static string showFrameList {
            get {
                return ResourceManager.GetString("showFrameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die start!! ähnelt.
        /// </summary>
        public static string startImportText {
            get {
                return ResourceManager.GetString("startImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visuals settings ähnelt.
        /// </summary>
        public static string VisualsSettingsDialogTitle {
            get {
                return ResourceManager.GetString("VisualsSettingsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sharpness
        ///Frequency
        ///Bouncyness ähnelt.
        /// </summary>
        public static string VisualsSettingsLabels {
            get {
                return ResourceManager.GetString("VisualsSettingsLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number could not be read, make sure to use the correct comma separator (&apos;,&apos; in german) ähnelt.
        /// </summary>
        public static string VisualsSettingsNumbersNotParsed {
            get {
                return ResourceManager.GetString("VisualsSettingsNumbersNotParsed", resourceCulture);
            }
        }
    }
}
